{
 "title": "ETA",
 "description": "Daten vom ETA Heizkessel",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Heizung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kessel und Abbrand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "expr": "Restsauerstoff{}", "legendFormat": "%" },
    { "expr": "Abgastemperatur{}", "legendFormat": "°C" }
   ]
  },
  {
   "title": "Volllaststunden",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Volllaststunden{}/(60*60)" }
   ]
  },
  {
   "title": "Heizkreis Vorlauf vs. Aussentemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "Heizkreisvorlauf{}", "legendFormat": "Vorlauf" },
    { "expr": "Aussentemperatur{}", "legendFormat": "Aussentemperatur" }
   ]
  },
  {
   "title": "Pufferladestand",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Pufferladezustand{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Solar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Leistung & Ertrag",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "Solarleistung{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "Kollektortemperatur{}", "legendFormat": "Kollektor" },
    { "expr": "Solarvorlauftemp{}", "legendFormat": "Vorlauf" },
    { "expr": "Solarruecklauf{}", "legendFormat": "Rücklauf" }
   ]
  },
  {
   "title": "Ertrag letzte 5 Tage",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "last_over_time(Solarertraggestern[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durchfluss Solar",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Solardurchfluss{}" }
   ]
  },
  {
   "title": "Aktuelle Leistung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Solarleistung{}" }
   ]
  },
  {
   "title": "Ertrag heute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Solarertragheute{}" }
   ]
  },
  {
   "title": "Solar Gesamtertrag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Solargesamt{}" }
   ]
  },
  { "title": "Puffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Verlauf Puffer Ladezustand",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "Pufferladezustand{}", "legendFormat": "Ladestand" }
   ]
  },
  {
   "title": "Puffer Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 21 },
   "targets": [
    { "expr": "PufferFuehler_1{}" },
    { "expr": "PufferFuehler_2{}" },
    { "expr": "PufferFuehler_3{}" },
    { "expr": "PufferFuehler_4{}" },
    { "expr": "PufferFuehler_5{}" }
   ]
  },
  {
   "title": "Speicher links",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PufferFuehler_1{}", "legendFormat": "oben" },
    { "expr": "PufferFuehler_2{}", "legendFormat": "mitte" },
    { "expr": "PufferFuehler_3{}", "legendFormat": "unten" }
   ]
  },
  {
   "title": "Speicher rechts",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PufferFuehler_4{}", "legendFormat": "oben" },
    { "expr": "PufferFuehler_5{}", "legendFormat": "unten" }
   ]
  },
  {
   "title": "FWM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true
  },
  {
   "title": "Warmwasserdurchfluss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Warmwasserdurchfluss{}", "legendFormat": "l/min" }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "Warmwassertemp{}" }
   ]
  }
 ]
}